In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
allsentence=["This pasta is very tasty and affordable",
             "This pasta is not very tasty and is affordable",
             "This pasta is very very delicious"]

In [5]:
CountVectorizer=CountVectorizer()
x = CountVectorizer.fit_transform(allsentence)
result=x.toarray()
result

array([[1, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 2, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 2]])

In [13]:
text=['Hello my name is james',
      'james this is my python notebook',
      'james trying to create a big dataset',
      'james of words to try different',
      'features of count vectorizer']

In [14]:
import pandas as pd
CountVectorizer=CountVectorizer()
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,big,count,create,dataset,different,features,hello,is,james,my,name,notebook,of,python,this,to,try,trying,vectorizer,words
0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,0,0,0,0,0
2,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0
3,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,1
4,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0

In [17]:
text = ["hello my name is dhanya","Hello my name is dhanya"]
CountVectorizer=CountVectorizer()
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   dhanya  hello  is  my  name
0       1      1   1   1     1
1       1      1   1   1     1

In [21]:
text = ["hello my name is dhanya","Hello my name is dhanya"]
CountVectorizer=CountVectorizer(lowercase=False)
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   Hello  dhanya  hello  is  my  name
0      0       1      1   1   1     1
1      1       1      0   1   1     1

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["hello my name is dhanya","Hello my name is dhanya"]
CountVectorizer=CountVectorizer(stop_words=['is','my'])
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   dhanya  hello  name
0       1      1     1
1       1      1     1

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["hello my name is dhanya","Hello my name is dhanya"]
CountVectorizer=CountVectorizer(stop_words='english')
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   dhanya  hello
0       1      1
1       1      1

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["This is the first document.","This document is the second document.","And this is the third one.","Is this tthe first document?",]
CountVectorizer=CountVectorizer()
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   and  document  first  is  one  second  the  third  this  tthe
0    0         1      1   1    0       0    1      0     1     0
1    0         2      0   1    0       1    1      0     1     0
2    1         0      0   1    1       0    1      1     1     0
3    0         1      1   1    0       0    0      0     1     1

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["This is the first document.","This document is the second document.","And this is the third one.","Is this tthe first document?",]
CountVectorizer=CountVectorizer(max_features=3)
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   document  is  this
0         1   1     1
1         2   1     1
2         0   1     1
3         1   1     1

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["This is the first document.","Is this the first document?",]
CountVectorizer=CountVectorizer()
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   document  first  is  the  this
0         1      1   1    1     1
1         1      1   1    1     1

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["This is the first document.","Is this the first document?",]
CountVectorizer=CountVectorizer(binary=True)
x = CountVectorizer.fit_transform(text)
result=x.toarray()
df=pd.DataFrame(data=result, columns = CountVectorizer.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   document  first  is  the  this
0         1      1   1    1     1
1         1      1   1    1     1